steps:
  - name: 'maven:3.6.3-openjdk-11'
    entrypoint: 'bash'
    env:
      - "DEBIAN_FRONTEND=noninteractive"
      - "SIGN_KEY=${_SIGN_KEY}"
    args: 
    - '-c'
    - |
      mkdir -p /root/.m2
      cat << EOF > /root/.m2/settings.xml
      <settings>
        <servers>
          <server>
            <id>ossrh</id>
            <username>${_OSSRH_USERNAME}</username>
            <password>${_OSSRH_PASSWORD}</password>
          </server>
          <server>
            <id>gpg.passphrase</id>
            <passphrase>${_SIGN_KEY_PASS}</passphrase>
          </server>
        </servers>
        <profiles>
          <profile>
            <id>sign</id>
            <properties>
                <gpg.passphrase>${_SIGN_KEY_PASS}</gpg.passphrase>
                <gpg.keyname>${_SIGN_KEY_ID}</gpg.keyname>
            </properties>
          </profile>
        </profiles>
        <activeProfiles>
          <activeProfile>sign</activeProfile>
        </activeProfiles>
      </settings>
      EOF
      echo $$SIGN_KEY | base64 --decode > /root/.m2/sign-key.asc
      gpg --import /root/.m2/sign-key.asc
      echo -e "5\ny\n" |  gpg --no-tty --command-fd 0 --expert --edit-key ${_SIGN_KEY_ID} trust
      gpg --list-keys
      cat /root/.m2/settings.xml
      mvn --no-transfer-progress -B versions:set -DremoveSnapshot &&
      mvn --no-transfer-progress -B clean package gpg:sign deploy