steps:
  - name: 'maven:3.6.3-openjdk-11'
    entrypoint: 'bash'
    env:
      - "DEBIAN_FRONTEND=noninteractive"
      - "SIGN_KEY=${_SIGN_KEY}"
      - "SIGN_KEY_PASS=${_SIGN_KEY_PASS}"
      - "SIGN_KEY_ID=${_SIGN_KEY_ID}"
    args: 
    - '-c'
    - |
      mkdir -p /root/.m2
      cat << EOF > /root/.m2/settings.xml
      <settings>
        <servers>
          <server>
            <id>ossrh</id>
            <username>${_OSSRH_USERNAME}</username>
            <password>${_OSSRH_PASSWORD}</password>
          </server>
        </servers>
      </settings>
      EOF
      mvn versions:set -DremoveSnapshot &&
      mvn sign:sign &&
      mvn -B clean package deploy 